apiVersion: v1 
kind: Pod 
metadata:
  name: web
  labels: 
    app: web
spec: 
  containers: 
  - name: web
    image: nginx_local:latest
    imagePullPolicy: Never
    volumeMounts:
    - name: app
      mountPath: /app
  initContainers:
  - name: init_web
    image: busybox:1.31.0
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
    - name: app
      mountPath: /app
  volumes:
  - name: app
    emptyDir: {}